# Generated by Django 3.2.18 on 2023-05-09 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ide.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Give a name to your program. 50 characters or fewer.', max_length=50, validators=[ide.utils.FileNameValidator()], verbose_name='program_name')),
                ('public', models.BooleanField(default=False, verbose_name='is_public')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_Script',
                'verbose_name_plural': 'User_Scripts',
                'db_table': 'User_Scripts',
            },
        ),
    ]
